export * from "./client";
export * from "./auth";
export * from "./system";
export * from "./bookings";
export * from "./match";
export * from "./users";
export * from "./handymen";
export * from "./availability";

// schema.ts is generated by pnpm gen:api
export type { paths, components } from "./schema";