import type { ImageSourcePropType } from 'react-native';

const skillImageSources: Record<string, ImageSourcePropType> = {
  appliance_installation: require('../../assets/skills/appliance_installation.png'),
  basic_electrical_troubleshooting: require('../../assets/skills/basic_electrical_troubleshooting.png'),
  cabinet_installation: require('../../assets/skills/cabinet_installation.png'),
  carpentry: require('../../assets/skills/carpentry.png'),
  caulking_sealing: require('../../assets/skills/caulking_sealing.png'),
  ceiling_fan_installation: require('../../assets/skills/ceiling_fan_installation.png'),
  closet_system_installation: require('../../assets/skills/closet_system_installation.png'),
  curtain_rod_installation: require('../../assets/skills/curtain_rod_installation.png'),
  deck_building_repair: require('../../assets/skills/deck_building_repair.png'),
  dishwasher_hookup: require('../../assets/skills/dishwasher_hookup.png'),
  doorbell_installation: require('../../assets/skills/doorbell_installation.png'),
  door_alignment_hinge_repair: require('../../assets/skills/door_alignment_hinge_repair.png'),
  door_installation: require('../../assets/skills/door_installation.png'),
  drain_unclogging: require('../../assets/skills/drain_unclogging.png'),
  drywall_installation: require('../../assets/skills/drywall_installation.png'),
  drywall_repair: require('../../assets/skills/drywall_repair.png'),
  ev_charger_installation: require('../../assets/skills/ev_charger_installation.png'),
  exterior_painting: require('../../assets/skills/exterior_painting.png'),
  faucet_installation_repair: require('../../assets/skills/faucet_installation_repair.png'),
  fence_installation_repair: require('../../assets/skills/fence_installation_repair.png'),
  fence_painting_staining: require('../../assets/skills/fence_painting_staining.png'),
  flatpack_assembly: require('../../assets/skills/flatpack_assembly.png'),
  flooring_installation: require('../../assets/skills/flooring_installation.png'),
  framing: require('../../assets/skills/framing.png'),
  furniture_assembly: require('../../assets/skills/furniture_assembly.png'),
  furniture_repair: require('../../assets/skills/furniture_repair.png'),
  garbage_disposal_installation: require('../../assets/skills/garbage_disposal_installation.png'),
  general_home_maintenance: require('../../assets/skills/general_home_maintenance.png'),
  grout_repair: require('../../assets/skills/grout_repair.png'),
  gutter_cleaning_repair: require('../../assets/skills/gutter_cleaning_repair.png'),
  interior_painting: require('../../assets/skills/interior_painting.png'),
  irrigation_repair: require('../../assets/skills/irrigation_repair.png'),
  landscaping_maintenance: require('../../assets/skills/landscaping_maintenance.png'),
  leak_detection_repair: require('../../assets/skills/leak_detection_repair.png'),
  led_lighting_upgrades: require('../../assets/skills/led_lighting_upgrades.png'),
  light_fixture_installation: require('../../assets/skills/light_fixture_installation.png'),
  lock_replacement_repair: require('../../assets/skills/lock_replacement_repair.png'),
  minor_roof_repairs: require('../../assets/skills/minor_roof_repairs.png'),
  mirror_mounting: require('../../assets/skills/mirror_mounting.png'),
  patio_installation: require('../../assets/skills/patio_installation.png'),
  picture_hanging: require('../../assets/skills/picture_hanging.png'),
  pipe_replacement: require('../../assets/skills/pipe_replacement.png'),
  plaster_repair: require('../../assets/skills/plaster_repair.png'),
  pressure_washing: require('../../assets/skills/pressure_washing.png'),
  security_camera_installation: require('../../assets/skills/security_camera_installation.png'),
  shed_assembly: require('../../assets/skills/shed_assembly.png'),
  shelf_installation: require('../../assets/skills/shelf_installation.png'),
  showerhead_installation: require('../../assets/skills/showerhead_installation.png'),
  sink_installation: require('../../assets/skills/sink_installation.png'),
  small_appliance_repair: require('../../assets/skills/small_appliance_repair.png'),
  smart_home_device_installation: require('../../assets/skills/smart_home_device_installation.png'),
  smart_switch_installation: require('../../assets/skills/smart_switch_installation.png'),
  solar_light_installation: require('../../assets/skills/solar_light_installation.png'),
  stair_repair: require('../../assets/skills/stair_repair.png'),
  switch_outlet_replacement: require('../../assets/skills/switch_outlet_replacement.png'),
  tile_installation: require('../../assets/skills/tile_installation.png'),
  tile_repair: require('../../assets/skills/tile_repair.png'),
  toilet_installation_repair: require('../../assets/skills/toilet_installation_repair.png'),
  trim_molding_installation: require('../../assets/skills/trim_molding_installation.png'),
  tv_wall_mounting: require('../../assets/skills/tv_wall_mounting.png'),
  wallpaper_installation_removal: require('../../assets/skills/wallpaper_installation_removal.png'),
  weatherproofing: require('../../assets/skills/weatherproofing.png'),
  weatherstripping_installation: require('../../assets/skills/weatherstripping_installation.png'),
  wifi_doorbell_installation: require('../../assets/skills/wifi_doorbell_installation.png'),
  window_installation: require('../../assets/skills/window_installation.png'),
  window_screen_repair: require('../../assets/skills/window_screen_repair.png'),
};

export function getSkillImageSource(skillKey: string) {
  return skillImageSources[skillKey];
}